# Created by: Bruno Lauze <brunolauze@msn.com>
# $FreeBSD: head/dotnet/Microsoft.Vsa/Makefile 402349 2015-12-10 08:15:09Z bruno $

PORTNAME=	Microsoft.AspNetCore.Diagnostics.Abstractions
PORTVERSION=	1.0.0.0

GH_PROJECT=	Diagnostics

.include <../../dotnet/aspnet/Makefile.common>


