# Created by: Bruno Lauze <brunolauze@msn.com>
# $FreeBSD: head/dotnet/Microsoft.Vsa/Makefile 402349 2015-12-10 08:15:09Z bruno $

PORTNAME=	Microsoft.AspNetCore.Diagnostics.Abstractions
PORTVERSION=	1.0.0.0

GH_PROJECT=	Diagnostics

OLD_LISTING+=		src/Microsoft.AspNetCore.Diagnostics.Abstractions/DiagnosticMessage.cs \
			src/Microsoft.AspNetCore.Diagnostics.Abstractions/ICompilationException.cs \
			src/Microsoft.AspNetCore.Diagnostics.Abstractions/IStatusCodeReExecuteFeature.cs \
			src/Microsoft.AspNetCore.Diagnostics.Abstractions/Properties/AssemblyInfo.cs \
			src/Microsoft.AspNetCore.Diagnostics.Abstractions/IStatusCodePagesFeature.cs \
			src/Microsoft.AspNetCore.Diagnostics.Abstractions/CompilationFailure.cs \
			src/Microsoft.AspNetCore.Diagnostics.Abstractions/IExceptionHandlerFeature.cs

.include <../../dotnet/aspnet/Makefile.common>


